/* firm.js -- Neutral/firm flavor events and portfolio-reactive events. */

import { shiftFaction } from '../faction-standing.js';

export const FIRM_EVENTS = [
    {
        id: 'barron_golfing',
        category: 'neutral',
        likelihood: 5,
        headline: 'President Barron spotted at Mar-a-Lago golf course for the third consecutive weekend. The Meridian Brief: "Nothing on the calendar. Enjoy the quiet."',
        params: { mu: 0.003 },
        magnitude: 'minor',
        when: (sim, world) => world.geopolitical.mideastEscalation < 2,
    },
    {
        id: 'barron_cryptic_tweet_1',
        category: 'neutral',
        likelihood: 5,
        headline: 'Barron posts cryptic late-night tweet: "Big things coming. Very big. Markets will love it." The Meridian Brief: "Ignore the tweet. Trade the tape."',
        params: { theta: 0.002 },
        magnitude: 'minor',
    },
    {
        id: 'barron_cryptic_tweet_2',
        category: 'neutral',
        likelihood: 4,
        headline: 'Barron tweets "The Fake News won\'t tell you, but PNTH is doing TREMENDOUS things for this country." Sharma: "Presidential stock tips. We live in interesting times." Stock ticks up briefly.',
        params: { mu: 0.003 },
        magnitude: 'minor',
    },
    {
        id: 'barron_speech_no_policy',
        category: 'neutral',
        likelihood: 4,
        headline: 'President Barron delivers 90-minute speech at rally; The Sentinel runs it live. The Meridian Brief: "90 minutes, zero policy substance. Markets unmoved."',
        params: { mu: -0.001 },
        magnitude: 'minor',
    },
    {
        id: 'gottlieb_ted_talk',
        category: 'neutral',
        likelihood: 3,
        headline: 'Gottlieb delivers TED talk on "Ethical AI in an Age of Acceleration"; standing ovation. Sharma tweets: "Eloquent as always. Markets don\'t care."',
        params: { mu: 0.004 },
        magnitude: 'minor',
        when: (sim, world) => world.pnth.ceoIsGottlieb,
    },
    {
        id: 'kassis_hackathon',
        category: 'neutral',
        likelihood: 3,
        headline: 'PNTH CTO Mira Kassis demos Atlas Sentinel capabilities at company hackathon; viral clip boosts employer brand. MarketWire picks it up.',
        params: { mu: 0.003 },
        magnitude: 'minor',
        when: (sim, world) => world.pnth.ctoIsMira,
    },
    {
        id: 'hartley_jackson_hole',
        category: 'neutral',
        likelihood: 3,
        headline: 'Fed Chair Hartley delivers measured Jackson Hole keynote; reaffirms data-dependent approach. Sharma\'s MarketWire recap: "Nothing new. She wants you to know she\'s watching the data. Markets shrug."',
        params: { mu: 0.002, theta: -0.002 },
        magnitude: 'minor',
        when: (sim, world) => !world.fed.hartleyFired,
    },
    {
        id: 'clay_book_tour',
        category: 'neutral',
        likelihood: 3,
        headline: 'Former President Clay\'s memoir "Against the Current" debuts at #1; Barron fires back on social media',
        params: { mu: -0.002 },
        magnitude: 'minor',
        effects: (world) => { world.election.barronApproval = Math.max(0, world.election.barronApproval - 1); },
    },
    {
        id: 'clay_university_speech',
        category: 'neutral',
        likelihood: 2,
        headline: 'Robin Clay gives commencement address at Georgetown, subtly criticizes current administration\'s trade policy. The Continental runs the transcript. The Sentinel ignores it.',
        params: { mu: 0.001 },
        magnitude: 'minor',
    },
    {
        id: 'congressional_recess',
        category: 'neutral',
        likelihood: 4,
        headline: 'Congress begins scheduled recess; no legislation expected for two weeks. The Meridian Brief: "Desk is flat into the recess. Nobody wants to be long risk with Congress out."',
        params: { theta: -0.002 },
        magnitude: 'minor',
        when: (sim, world) => world.investigations.impeachmentStage === 0,
    },
    {
        id: 'zhaowei_conference',
        category: 'neutral',
        likelihood: 3,
        headline: 'Zhaowei CEO Liang Wei showcases new chip architecture at Beijing AI Forum; Sharma: "The Zhaowei gap is narrowing. Kassis knows it."',
        params: { mu: -0.002 },
        magnitude: 'minor',
    },
    {
        id: 'markets_drift_sideways_1',
        category: 'neutral',
        likelihood: 6,
        headline: 'Markets drift sideways on light volume. The Meridian Brief: "Quiet tape. This is usually when something happens."',
        params: { mu: 0.001, theta: -0.001 },
        magnitude: 'minor',
    },
    {
        id: 'markets_drift_sideways_2',
        category: 'neutral',
        likelihood: 6,
        headline: 'Another quiet session as major indices trade in a tight range; VIX slips below 14. The Meridian Brief: "Vol sellers are getting paid. Enjoy it while it lasts."',
        params: { theta: -0.002 },
        magnitude: 'minor',
    },
    {
        id: 'markets_drift_sideways_3',
        category: 'neutral',
        likelihood: 5,
        headline: 'Low-conviction session: breadth flat, volume below 30-day average. The Meridian Brief: "No leadership, no conviction. Market is waiting for Malhotra\'s earnings call."',
        params: { mu: 0.002 },
        magnitude: 'minor',
    },
    {
        id: 'holiday_thin_volume',
        category: 'neutral',
        likelihood: 4,
        headline: 'Holiday-shortened week sees thin volumes; institutional desks running skeleton crews. The Meridian Brief: "Half the Street is at the Hamptons. The other half wishes they were."',
        params: { theta: -0.003, lambda: -0.1 },
        magnitude: 'minor',
    },
    {
        id: 'sector_rotation_flavor',
        category: 'neutral',
        likelihood: 4,
        headline: 'Sector rotation continues as money flows from growth to value. The Meridian Brief: "Rotation, not distribution. Net index impact negligible."',
        params: { mu: 0.002 },
        magnitude: 'minor',
    },
    {
        id: 'opex_positioning',
        category: 'neutral',
        likelihood: 3,
        headline: 'Options expiration approaching; dealers adjust hedges as gamma exposure shifts near key strikes. The Meridian Brief flags unusual activity ahead of Malhotra\'s next earnings call.',
        params: { theta: 0.003 },
        magnitude: 'minor',
    },
    {
        id: 'overseas_markets_flat',
        category: 'neutral',
        likelihood: 5,
        headline: 'European and Asian bourses close mixed; no clear signal for U.S. open. The Meridian Brief: "Overnight session says nothing. We trade our own book."',
        params: { mu: 0.001 },
        magnitude: 'minor',
    },
    {
        id: 'buyback_season',
        category: 'neutral',
        likelihood: 3,
        headline: 'Corporate buyback window reopens post-earnings; S&P constituents authorized $180B in repurchases this quarter. Malhotra\'s buyback program is among the largest.',
        params: { mu: 0.005, theta: -0.002 },
        magnitude: 'minor',
    },
    {
        id: 'bond_auction_tepid',
        category: 'neutral',
        likelihood: 4,
        headline: '10-year Treasury auction draws tepid demand; tail of 1.2bps, bid-to-cover at 2.31x. Sharma on MarketWire: "The bond vigilantes are sending a message."',
        params: { b: 0.001, sigmaR: 0.001 },
        magnitude: 'minor',
    },
    {
        id: 'retail_sales_inline',
        category: 'neutral',
        likelihood: 4,
        headline: 'Retail sales come in exactly at consensus (+0.3% m/m); no revision to prior month. The Meridian Brief: "In-line data, in-line market. Next."',
        params: { mu: 0.002 },
        magnitude: 'minor',
    },
    {
        id: 'pnth_investor_conference',
        category: 'neutral',
        likelihood: 3,
        headline: 'PNTH holds annual investor conference; Gottlieb reiterates long-term Atlas Sentinel vision, no guidance change. Malhotra handles the Q&A. Dirks skips the event.',
        params: { mu: 0.004, theta: -0.001 },
        magnitude: 'minor',
        when: (sim, world) => world.pnth.ceoIsGottlieb,
    },
    {
        id: 'meme_stock_day',
        category: 'neutral',
        likelihood: 3,
        headline: 'Retail traders pile into meme stocks again; social media forums light up. The Meridian Brief: "The meme crowd is back. Index impact minimal but the vol desk is watching."',
        params: { theta: 0.003, xi: 0.01 },
        magnitude: 'minor',
    },
    {
        id: 'mixed_economic_data',
        category: 'neutral',
        likelihood: 5,
        headline: 'Mixed economic signals: jobless claims tick up while ISM manufacturing beats. The Meridian Brief: "Data is contradicting itself. Markets chop in a narrow range."',
        params: { mu: 0.001 },
        magnitude: 'minor',
    },
    {
        id: 'approval_mean_revert',
        category: 'neutral',
        likelihood: 4,
        headline: 'MarketWire tracking poll shows slight shift in Barron approval; The Sentinel and The Continental spin opposite narratives from the same data',
        params: {},
        magnitude: 'minor',
        effects: (world) => {
            // Nudge approval gently toward 45 to prevent extreme early drift
            if (world.election.barronApproval > 50) {
                world.election.barronApproval -= 1;
            } else if (world.election.barronApproval < 40) {
                world.election.barronApproval += 1;
            }
        },
    },

    // ── Low-firmStanding consequence events ──
    {
        id: 'firm_capital_cut',
        category: 'neutral',
        likelihood: 3,
        headline: 'Webb cuts your risk allocation by 20%. "Until we see consistent performance."',
        magnitude: 'moderate',
        when: (sim, world, congress, ctx) => ctx.factions.firmStanding <= 30,
        effects: () => { shiftFaction('firmStanding', -2); },
    },
    {
        id: 'firm_riggs_promoted',
        category: 'neutral',
        likelihood: 1,
        headline: 'Riggs gets the corner office. Vasquez says it\'s "just logistics." Nobody believes her.',
        magnitude: 'minor',
        oneShot: true,
        when: (sim, world, congress, ctx) => ctx.factions.firmStanding <= 35 && sim.day > 300,
        effects: () => { shiftFaction('firmStanding', -3); },
    },
    {
        id: 'firm_vasquez_warning',
        category: 'neutral',
        likelihood: 2,
        headline: 'Vasquez takes you aside: "I went out on a limb to bring you here. Don\'t make me regret it."',
        magnitude: 'minor',
        when: (sim, world, congress, ctx) => ctx.factions.firmStanding <= 40 && ctx.factions.firmStanding > 25 && sim.day > 200,
    },
    {
        id: 'firm_capital_boost',
        category: 'neutral',
        likelihood: 2,
        headline: 'Webb increases your allocation. "You\'ve earned more rope. Don\'t hang yourself with it."',
        magnitude: 'minor',
        when: (sim, world, congress, ctx) => ctx.factions.firmStanding >= 80,
        effects: () => { shiftFaction('firmStanding', 1); },
    },

    // ── Portfolio-reactive events ──
    {
        id: 'portfolio_whale_whispers',
        category: 'neutral',
        likelihood: 2,
        headline: 'Riggs leans over: "People are talking about your book. The Street knows when someone\'s swinging big."',
        magnitude: 'minor',
        when: (sim, world, congress, ctx) => ctx.portfolio.grossLeverage > 3 && ctx.factions.firmStanding > 40,
        effects: () => { shiftFaction('regulatoryExposure', 2); shiftFaction('firmStanding', -2); },
    },
    {
        id: 'portfolio_drawdown_notice',
        category: 'neutral',
        likelihood: 2.5,
        headline: 'Webb stops by your desk. He doesn\'t say anything. He just looks at your screen and leaves.',
        magnitude: 'minor',
        when: (sim, world, congress, ctx) => ctx.portfolio.pnlPct < -0.15 && ctx.factions.firmStanding < 50,
        effects: () => { shiftFaction('firmStanding', -3); },
    },
    {
        id: 'portfolio_streak_recognized',
        category: 'neutral',
        likelihood: 1.5,
        headline: 'Vasquez mentions your name in the partners\' meeting. "Best risk-adjusted returns on the floor."',
        magnitude: 'minor',
        when: (sim, world, congress, ctx) => ctx.portfolio.pnlPct > 0.3 && ctx.portfolio.grossLeverage < 2,
        effects: () => { shiftFaction('firmStanding', 4); },
    },
    {
        id: 'portfolio_flat_book',
        category: 'neutral',
        likelihood: 2,
        headline: 'Webb asks why your book is empty. "We\'re not paying you to watch."',
        magnitude: 'minor',
        when: (sim, world, congress, ctx) => ctx.portfolio.positionCount === 0 && sim.day > 280,
        effects: () => { shiftFaction('firmStanding', -2); },
    },
];
